module.exports = {
    "/m/04rlf": "music",
    "/m/02mscn": "christian music",
    "/m/0ggq0m": "classical music",
    "/m/01lyv": "country",
    "/m/02lkt": "electronic music",
    "/m/0glt670": "hip hop music",
    "/m/05rwpb": "independent music",
    "/m/03_d0": "jazz",
    "/m/028sqc": "music of asia",
    "/m/0g293": "music of latin america",
    "/m/064t9": "pop music",
    "/m/06cqb": "reggae",
    "/m/06j6l": "rhythm and blues",
    "/m/06by7": "rock music",
    "/m/0gywn": "soul music",
    "/m/0bzvm2": "gaming",
    "/m/025zzc": "action game",
    "/m/02ntfj": "action-adventure game",
    "/m/0b1vjn": "casual game",
    "/m/02hygl": "music video game",
    "/m/04q1x3q": "puzzle video game",
    "/m/01sjng": "racing video game",
    "/m/0403l3g": "role-playing video game",
    "/m/021bp2": "simulation video game",
    "/m/022dc6": "sports game",
    "/m/03hf_rm": "strategy video game",
    "/m/06ntj": "sports",
    "/m/0jm_": "american football",
    "/m/018jz": "baseball",
    "/m/018w8": "basketball",
    "/m/01cgz": "boxing",
    "/m/09xp_": "cricket",
    "/m/02vx4": "football",
    "/m/037hz": "golf",
    "/m/03tmr": "ice hockey",
    "/m/01h7lh": "mixed martial arts",
    "/m/0410tth": "motorsport",
    "/m/07bs0": "tennis",
    "/m/07_53": "volleyball",
    "/m/02jjt": "entertainment",
    "/m/09kqc": "humor",
    "/m/02vxn": "movies",
    "/m/05qjc": "performing arts",
    "/m/066wd": "professional wrestling",
    "/m/0f2f9": "tv shows",
    "/m/019_rr": "lifestyle",
    "/m/032tl": "fashion",
    "/m/027x7n": "fitness",
    "/m/02wbm": "food",
    "/m/03glg": "hobby",
    "/m/068hy": "pets",
    "/m/041xxh": "physical attractiveness [beauty]",
    "/m/07c1v": "technology",
    "/m/07bxq": "tourism",
    "/m/07yv9": "vehicles",
    "/m/098wr": "society",
    "/m/09s1f": "business",
    "/m/0kt51": "health",
    "/m/01h6rj": "military",
    "/m/05qt0": "politics",
    "/m/06bvp": "religion",
    "/m/01k8wb": "knowledge"
}